import { readFile, writeFile } from "fs/promises";
import { fileURLToPath } from "url";

const path = (relative) => fileURLToPath(new URL(relative, import.meta.url));

const hospitals = JSON.parse(await readFile(path("../output/hospitals.json"), "utf8"));
const documents = JSON.parse(await readFile(path("../output/documentMatches.json"), "utf8"));
const logos = {};
for (const hospital of hospitals) {
  if (!hospital.logoPath) continue;
  const file = hospital.logoPath.split("/").pop();
  logos[hospital.logoPath] = `data:image/png;base64,${(await readFile(path(`../logos/${file}`))).toString("base64")}`;
}

const html = `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NABH Hospital Demo</title><style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');:root{font-family:Poppins,sans-serif;color:#30375f;background:#eef0ff}*{box-sizing:border-box}body{margin:0}.nav{align-items:center;background:#30375f;display:flex;gap:6px;padding:10px 20px}.nav img{background:#fff;border-radius:4px;height:42px;object-fit:contain;padding:3px;width:64px}.nav span{color:#fff;font-size:13px;font-weight:600;margin-right:auto}.nav button{background:transparent;border:0;color:#e7e9ff;cursor:pointer;padding:9px 11px}.nav button.active{background:#fff;color:#3547d1}.main{max-width:1200px;margin:auto;padding:34px 20px}.login{background:#fff;border-radius:8px;box-shadow:0 18px 40px #4c57942b;margin:10vh auto;padding:30px;width:min(420px,100%)}h1,h2{margin:0}.eyebrow{color:#6570b5;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.intro{color:#68719c;font-size:13px}.brand{align-items:center;display:flex;gap:14px;margin-bottom:24px}.brand img{background:#fff;border:1px solid #d9dcf3;border-radius:6px;height:96px;object-fit:contain;padding:6px;width:96px}.grid{display:grid;gap:20px;grid-template-columns:280px 1fr}.panel{background:#fff;border-radius:8px;box-shadow:0 14px 30px #4c57941f;padding:20px}.search,input{border:1px solid #dce0f5;border-radius:5px;font:inherit;padding:9px;width:100%}.list button{align-items:center;background:transparent;border:0;border-top:1px solid #eef0fb;color:#37406e;cursor:pointer;display:flex;gap:10px;padding:10px 4px;text-align:left;width:100%}.list img{background:#fff;border:1px solid #e0e3f8;border-radius:4px;height:50px;object-fit:contain;padding:3px;width:50px}.list small,.card small{color:#7780aa;display:block}.cards{display:grid;gap:10px;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:14px}.card{background:#f8f9ff;border:1px solid #e7e9fa;border-radius:5px;padding:13px}.card p,.role p{color:#5663b2;font-size:11px;margin:4px 0}.role{border-top:1px solid #edf0fb;padding:12px 0}.primary{background:#3547d1;border:0;border-radius:5px;color:#fff;cursor:pointer;font:600 13px Poppins;padding:10px 14px}.hint{color:#68719c;font-size:12px;line-height:1.7}@media(max-width:720px){.grid,.cards{grid-template-columns:1fr}.nav{flex-wrap:wrap}}
</style></head><body><div id="app"></div><script>
const hospitals=${JSON.stringify(hospitals)};const documents=${JSON.stringify(documents)};const logos=${JSON.stringify(logos)};let session=null,view='users',selected=hospitals[0],query='';
const logo=h=>logos[h.logoPath]||'';const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function render(){const app=document.querySelector('#app');if(!session){app.innerHTML='<main class="login"><p class="eyebrow">Static demo</p><h1>NABH sign in</h1><p class="hint">Super Admin: superadmin / Admin@123<br>Hospital Admin: aarogyam-admin / Hospital@123</p><label>User ID<input id="id" value="superadmin"></label><label>Password<input id="pw" type="password" value="Admin@123"></label><br><button class="primary" onclick="login()">Sign in</button></main>';return}app.innerHTML='<nav class="nav">'+(session.role==='Hospital Administrator'?'<img src="'+logo(selected)+'">':'')+'<span>'+esc(session.role==='Super Admin'?'Super Admin':selected.name)+'</span>'+(session.role==='Super Admin'?'<button class="active">Hospitals</button>':'<button class="'+(view==='users'?'active':'')+'" onclick="view=&quot;users&quot;;render()">Users</button><button class="'+(view==='roles'?'active':'')+'" onclick="view=&quot;roles&quot;;render()">Roles</button><button class="'+(view==='documents'?'active':'')+'" onclick="view=&quot;documents&quot;;render()">Documents</button>')+'<button onclick="session=null;render()">Sign out</button></nav><main class="main">'+(session.role==='Super Admin'?registry():view==='users'?users():view==='roles'?roles():docs())+'</main>'}
function login(){const id=document.querySelector('#id').value.toLowerCase(),pw=document.querySelector('#pw').value;if(id==='superadmin'&&pw==='Admin@123')session={role:'Super Admin'};else if(id.endsWith('-admin')&&pw==='Hospital@123'){selected=hospitals.find(h=>h.code.toLowerCase()===id.slice(0,-6));if(selected)session={role:'Hospital Administrator'}}if(!session)alert('Invalid demo account');render()}
function registry(){const list=hospitals.filter(h=>(h.name+h.code+h.location).toLowerCase().includes(query.toLowerCase()));return '<div class="brand"><h1>Hospital registry</h1></div><div class="grid"><section class="panel list"><input class="search" placeholder="Search hospitals" oninput="query=this.value;render()">'+list.map(h=>'<button onclick="selected=h;render()"><img src="'+logo(h)+'"><span><strong>'+esc(h.name)+'</strong><small>'+esc(h.code)+' · '+esc(h.location)+'</small></span></button>').join('')+'</section><section class="panel"><h2>'+esc(selected.name)+'</h2><p class="intro">'+esc(selected.details.addressLine1)+'<br>'+esc(selected.location)+'</p><p class="hint">'+esc(selected.details.hospitalType)+' · '+esc(selected.details.operationalBeds)+' operational beds</p></section></div>'}
function users(){const list=selected.users.filter(u=>(u.name+u.role+u.department+u.employeeId).toLowerCase().includes(query.toLowerCase()));return '<div class="brand"><img src="'+logo(selected)+'"><div><p class="eyebrow">Hospital workspace</p><h1>User management</h1></div></div><section class="panel"><button class="primary" onclick="alert(&quot;Static demo: Add User workflow&quot;)">Add user</button><input class="search" placeholder="Search users" oninput="query=this.value;render()"><div class="cards">'+list.map(u=>'<article class="card"><strong>'+esc(u.name)+'</strong><p>'+esc(u.role)+' · '+esc(u.department)+'</p><small>'+esc(u.employeeId)+' · '+esc(u.email)+'</small></article>').join('')+'</div></section>'}
function roles(){return '<div class="brand"><img src="'+logo(selected)+'"><div><p class="eyebrow">Hospital workspace</p><h1>Role management</h1></div></div><section class="panel">'+(selected.roles||[]).map(r=>'<article class="role"><strong>'+esc(r.name)+'</strong><p>'+esc(Object.entries(r.documentAccess||{}).filter(x=>x[1].length).map(x=>x[0]+': '+x[1].length).join(' · ')||'No documents assigned')+'</p></article>').join('')+'</section>'}
function docs(){return '<div class="brand"><img src="'+logo(selected)+'"><div><p class="eyebrow">Hospital workspace</p><h1>'+esc(selected.name)+' documents</h1></div></div><section class="panel">'+Object.entries(documents).slice(0,10).map(([name,items])=>'<article class="role"><strong>'+esc(name)+'</strong><p>'+items.length+' documents</p></article>').join('')+'</section>'}render();
</script></body></html>`;
await writeFile(path("../prototype.html"), html);
console.log(`Static demo prototype generated: ${path("../prototype.html")}`);
